---

- hosts: homelab-k3s-nodes
  pre_tasks:

  - name: install updates (CentOS)
    tags: os-updates
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: homelab-nodes
  user: root
  sudo: yes
  tasks:

  - name: install qemu-guest-agent
    package:
      name: qemu-guest-agent

  - name: Enable service qemu-guest-agent
    ansible.builtin.service:
      name: qemu-guest-agent
      enabled: yes