---

- hosts: homelab-k3s-nodes
  pre_tasks:

    - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
 
- hosts: homelab-k3s-nodes
  user: root
  sudo: yes
  tasks:

  - name: install qemu-guest-agent
    package:
      name: qemu-guest-agent

  - name: Enable service qemu-guest-agent
    ansible.builtin.service:
      name: qemu-guest-agent
      enabled: yes