---

- hosts: proxmox
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"
